# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-19 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cian_id', models.IntegerField(unique=True)),
                ('cian_user_id', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(null=True)),
                ('price_usd', models.IntegerField(null=True)),
                ('price_eur', models.IntegerField(null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_top', models.BooleanField(default=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=1024)),
                ('is_moulage', models.BooleanField(default=False)),
                ('edited', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=2048)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='cian.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cian.Offer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OffersFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048)),
                ('max_pages', models.IntegerField(default=3)),
                ('query', models.TextField(blank=True, null=True)),
                ('json_query', models.TextField(blank=True, null=True)),
                ('offers_count', models.IntegerField(blank=True, null=True)),
                ('min_price', models.IntegerField(blank=True, null=True)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('is_updating', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OffersUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(b'waiting', '\u041e\u0436\u0438\u0434\u0430\u043d\u0438\u0435'), (b'processing', '\u041e\u0431\u043d\u043e\u0432\u043b\u044f\u0435\u0442\u0441\u044f'), (b'success', '\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u0443\u0441\u043f\u0435\u0448\u043d\u043e'), (b'retry', 'cian \u043d\u0435 \u0434\u0430\u0451\u0442'), (b'error', '\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430')], default=b'waiting', max_length=16)),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cian.OffersFilter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cian_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('is_agent', models.BooleanField(default=False)),
                ('logo', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('phones', models.ManyToManyField(blank=True, related_name='retailers', to='cian.Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetailerAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=1024)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='cian.Retailer')),
            ],
        ),
        migrations.AddField(
            model_name='offerposition',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cian.OffersFilter'),
        ),
        migrations.AddField(
            model_name='offerposition',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cian.Offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='cian.Phone'),
        ),
        migrations.AlterUniqueTogether(
            name='retailerattribute',
            unique_together=set([('retailer', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='offerattribute',
            unique_together=set([('offer', 'key')]),
        ),
    ]
