# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-19 00:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control_offers', models.ManyToManyField(blank=True, related_name='controled', to='cian.Offer')),
                ('offers', models.ManyToManyField(blank=True, related_name='viewers', to='cian.Offer')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to='cian.Phone')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrokerFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='office.Broker')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observed', to='cian.OffersFilter')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(b'default', '\u041f\u0440\u043e\u0441\u0442\u043e\u0435'), (b'filter_min_price_changed', '\u0418\u0437\u043c\u0435\u043d\u0438\u043b\u0430\u0441\u044c \u043c\u0438\u043d\u0438\u043c\u0430\u043b\u044c\u043d\u0430\u044f \u0446\u0435\u043d\u0430'), (b'filter_count_changed', '\u0418\u0437\u043c\u0435\u043d\u0438\u043b\u043e\u0441\u044c \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043e\u0431\u044a\u0435\u043a\u0442\u043e\u0432'), (b'position_changed', '\u0418\u0437\u043c\u0435\u043d\u0438\u043b\u0430\u0441\u044c \u043f\u043e\u0437\u0438\u0446\u0438\u044f \u0432\u0430\u0448\u0435\u0433\u043e \u043e\u0431\u044a\u0435\u043a\u0442\u0430'), (b'new_watching_offer', '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d \u043e\u0431\u044a\u0435\u043a\u0442 \u0434\u043b\u044f \u043d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u044f'), (b'control_position_changed', '\u0418\u0437\u043c\u0435\u043d\u0438\u043b\u0430\u0441\u044c \u043f\u043e\u0437\u0438\u0446\u0438\u044f \u043e\u0431\u044a\u0435\u043a\u0442\u0430 \u043d\u0430 \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u0435'), (b'control_price_changed', '\u0418\u0437\u043c\u0435\u043d\u0438\u043b\u0430\u0441\u044c \u0446\u0435\u043d\u0430 \u043e\u0431\u044a\u0435\u043a\u0442\u0430 \u043d\u0430 \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u0435'), (b'control_istop_changed', '\u0418\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0435 \u0422\u041e\u041f \u0441\u0442\u0430\u0442\u0443\u0441 \u0443 \u043e\u0431\u044a\u0435\u043a\u0442\u0430 \u043d\u0430 \u043a\u043e\u0442\u0440\u043e\u043b\u0435')], default=b'default', max_length=32)),
                ('values', models.CharField(blank=True, max_length=1024, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='office.Broker')),
                ('offers_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cian.OffersFilter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='brokerfilter',
            unique_together=set([('broker', 'filter')]),
        ),
    ]
