# Generated by Django 3.2.9 on 2021-11-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_viewed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('default', 'Простое'), ('filter_min_price_changed', 'Изменилась минимальная цена'), ('filter_count_changed', 'Изменилось количество объектов'), ('position_changed', 'Изменилась позиция вашего объекта'), ('new_watching_offer', 'Добавлен объект для наблюдения'), ('control_position_changed', 'Изменилась позиция объекта на контроле'), ('control_price_changed', 'Изменилась цена объекта на контроле'), ('control_istop_changed', 'Изменение ТОП статус у объекта на котроле')], default='default', max_length=32),
        ),
    ]
